### ISSUE TITLE
Blank heatmap?

### ISSUE THREAD

**Issue by milnus** [shimbalama/post_fastGEAR#3]
Hi, 
I'm trying to produce a heatmap from the output of fastGEAR. However the heatmap printed is just a blank plot. The _count and _scatter plots works fine. I do not get any errors when running the script. Any idea on what to check or fix to get it working?

Cheers,
Magnus

**Comment by shimbalama** [comment]
HI - not sure sorry. the no error error is always the worst. if you are able to share your data and your cmd line calls I can try replicate it.

Liam

**Comment by milnus** [comment]
All good! Thanks! I have made a small example, that I've tested and it 'works'. 
The command I used: `python3 post_fastGEAR.py -i fastgear_results/ -o test_post_fastgear -p ordering.txt`.
There is also a .yml file with info on the conda environment I used to run the script.

[github_issue_3.zip](https://github.com/shimbalama/post_fastGEAR/files/5587766/github_issue_3.zip)

**Comment by shimbalama** [comment]
I'll try get to this on the weekend

**Comment by shimbalama** [comment]
the issue is that neither hutU or group_1996 is in lineage_information.txt. you need to use the SRR ids.
