### ISSUE TITLE
'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by smb20200615** [shimbalama/post_fastGEAR#4]
Hello,

I get the following error when running python post_fastGEAR2.py -i . -o out. Can you tell why that is so?

Best wishes,

**Comment by shimbalama** [comment]
Hi, 

Sorry for the delayed response.

The help for -i says 'FastGEAR folder. Should have folders with gene names only no suffix or prefix'. You entered '.'. Does that meet the requirements? If so plz send me some sample data so I can reproduce the error.

Liam
